const Strings = {
  common: {
    simplepin: 'Simplepin',
    cancel: 'Cancel',
    ok: 'OK',
    delete: 'Delete',
    deletePost: 'Delte bookmark?',
    edit: 'Edit',
    markAs: 'Mark as',
    search: 'Search…',
    noPosts: 'No bookmarks',
    noPostsMessage: 'Add bookmarks directly from the browser or by tapping the add button below',
    noResults: 'No results for',
    tryAgain: 'Try again',
    showSimilar: 'Show similar',
  },
  error: {
    loginFailed: 'Login failed',
    incorrectToken: 'Incorrect API token',
    invalidToken: 'Invalid API token',
    logInAgain: 'Please log in again',
    tooManyRequests: 'Too many requests',
    tryAgainLater: 'Please try again later',
    troubleConnecting: 'Trouble connecting to Pinboard',
    pinboardDown: 'Pinboard might be down, please try again later',
    somethingWrong: 'Something went wrong',
  },
  login: {
    title: 'Welcome!',
    text: 'Simplepin makes reading and managing your Pinboard bookmarks easy',
    placeholder: 'Enter your API token',
    button: 'Log in',
    token: 'Show API token',
  },
  posts: {
    title: 'Bookmarks',
    all: 'All',
    private: 'Private',
    public: 'Public',
    unread: 'Unread',
    starred: 'Starred',
  },
  settings: {
    title: 'Settings',
    general: 'General',
    privateByDefault: 'Private by default',
    unreadByDefault: 'Unread by default',
    markAsReadWhenOpened: 'Mark as read when opened',
    browser: 'Browser',
    defaultBrowser: 'Default browser',
    openLinksInDefaultBrowser: 'Open links in default browser',
    display: 'Display',
    exactDates: 'Exact dates',
    sortTagsAlphabetically: 'Sort tags alphabetically',
    other: 'Other',
    version: 'Version',
    logout: 'Log out',
  },
  add: {
    titleAdd: 'Add bookmark',
    titleEdit: 'Edit bookmark',
    discardAdd: 'Discard this bookmark?',
    discardEdit: 'Discard unsaved changes to this bookmark?',
    placeholderHref: 'URL',
    placeholderDescription: 'Title',
    placeholderExtended: 'Description',
    placeholderTags: 'Tags',
    readLater: 'Read later',
    buttonAdd: 'Add',
    buttonSave: 'Save',
  },
}

export default Strings
